const dummyData = [
    {
        roomNumber: 101,
        block: "A",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 102,
        block: "B",
        size: 5,
        slots: 5,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 103,
        block: "C",
        size: 3,
        slots: 3,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 104,
        block: "A",
        size: 2,
        slots: 2,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 105,
        block: "B",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 106,
        block: "C",
        size: 5,
        slots: 5,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 107,
        block: "A",
        size: 3,
        slots: 3,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 108,
        block: "B",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 109,
        block: "C",
        size: 5,
        slots: 5,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 110,
        block: "A",
        size: 3,
        slots: 3,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 201,
        block: "B",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 202,
        block: "C",
        size: 5,
        slots: 5,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 203,
        block: "A",
        size: 3,
        slots: 3,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 204,
        block: "B",
        size: 5,
        slots: 5,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 205,
        block: "C",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 206,
        block: "A",
        size: 2,
        slots: 2,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 207,
        block: "B",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 208,
        block: "C",
        size: 3,
        slots: 3,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
    {
        roomNumber: 209,
        block: "A",
        size: 5,
        slots: 5,
        currentSize: 0,
        isFull: false,
        roomType: "girls",
    },
    {
        roomNumber: 210,
        block: "B",
        size: 4,
        slots: 4,
        currentSize: 0,
        isFull: false,
        roomType: "boys",
    },
];

export default dummyData;
